# Generated by Django 3.1 on 2020-08-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
